### ISSUE TITLE
关于AE网络的重构损失问题

### ISSUE THREAD

**Issue by HanAccount** [uqzhichen/SDGZSL#5]
你好：
![image](https://user-images.githubusercontent.com/87269265/147668157-55466956-d440-4e01-befa-266ed29488cc.png)
我看到代码中的重构损失rec是将x1和x2都与原始特征X来做重构的，不过x1是由x_mean通过AE网络
来生成的，所以在重构损失中对于x1的损失为什么不是mse(x1,x_mean)呢？

**Comment by uqzhichen** [comment]
Hi Han,

Happy new year, and thank you for your question. Actually, the reconstructed x_mean is supposed to be identical to X, but there is of course some information missing within x_mean after reconstruction. As we want to reconstruct x1 from the disentangled hs and hn, it would be better to provide the ground-truth supervision (i.e., X) rather than the reconstructed x_mean. 

Regards,
Zhi

**Comment by HanAccount** [comment]
thanks！Happy New Year to You！
